name: Build and Deploy to TestFlight

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: macos-latest
    env:
      APPSTORE_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
      APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      IPHONEOS_DEPLOYMENT_TARGET: ${{ vars.IPHONEOS_DEPLOYMENT_TARGET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Create App Store Connect API key file
        if: github.event_name == 'push'
        run: |
          # write the private key to a file in the workspace root
          cat <<EOF > AuthKey.p8
          $APPSTORE_API_PRIVATE_KEY
          EOF
          echo "Wrote AuthKey.p8 to $(pwd)/AuthKey.p8"

      - name: Archive iOS App
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            # Full archive for deployment
            AUTH_KEY_PATH="$(pwd)/AuthKey.p8"
            echo "Using authenticationKeyPath: $AUTH_KEY_PATH"
            xcodebuild \
              -project HueKnew.xcodeproj \
              -scheme HueKnew \
              -configuration Release \
              -destination 'generic/platform=iOS' \
              -archivePath build/HueKnew.xcarchive \
              -allowProvisioningUpdates \
              -authenticationKeyPath "$AUTH_KEY_PATH" \
              -authenticationKeyID "$APPSTORE_API_KEY_ID" \
              -authenticationKeyIssuerID "$APPSTORE_ISSUER_ID" \
              IPHONEOS_DEPLOYMENT_TARGET="$IPHONEOS_DEPLOYMENT_TARGET" \
              archive
          else
            # Simple build for PR validation
            echo "Building for PR validation..."
            xcodebuild \
              -project HueKnew.xcodeproj \
              -scheme HueKnew \
              -configuration Release \
              -destination 'generic/platform=iOS' \
              -derivedDataPath build \
              clean build
          fi

      - name: Create Export Options
        if: github.event_name == 'push'
        run: |
          cat > exportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF

      - name: Export iOS App
        if: github.event_name == 'push'
        run: |
          xcodebuild -exportArchive \
            -archivePath build/HueKnew.xcarchive \
            -exportPath build/export \
            -exportOptionsPlist exportOptions.plist

      - name: Upload to TestFlight
        if: github.event_name == 'push'
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: 'build/export/HueKnew.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
